name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # TODO Uncomment one of the below to cache dependencies
        # cache: npm
        # cache: yarn
    # TODO Uncomment one of the below
    ### npm {{{
    # - run: npm ci
    # - run: npm run lint
    # - run: npm run build --if-present
    # - run: npm run build:docs -- --treatWarningsAsErrors
    # - name: Test and Generate Coverage
    #   run: npm test
    ### }}} npm
    ### yarn {{{
    # - run: yarn install --frozen-lockfile
    # - run: yarn lint
    # - run: yarn build
    # - run: yarn build:docs --treatWarningsAsErrors
    # - name: Test and Generate Coverage
    #   run: yarn test
    ### }}} yarn
    # TODO Uncomment to use codecov
    # - name: Upload Coverage Report
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
